name: Chiletrabajos BOT
env:
  DS_WEBHOOK: ${{ secrets.DS_WEBHOOK }}
  URL_TRABAJO: ${{ secrets.URL_TRABAJO }}

on:
  schedule:
    - cron: '*/15 * * * *'  
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt

      - name: Ejecutar script
        run: |
          python trabajos_bot.py

      - name: Guardar archivo JSON con los trabajos ya enviados
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}
          git add vistos.json
          git diff --cached --quiet || git commit -m "Actualiza trabajos enviados [bot]"
          git push origin main

